name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - libffi=3.4.2
  - libzlib-wapi=1.2.12
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.10.4
  - python_abi=3.10
  - setuptools=61.2.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.2.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - colorama==0.4.5
    - docopt==0.6.2
    - flask==2.2.2
    - flask-login==0.6.2
    - flask-sqlalchemy==2.5.1
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==1.1.2
    - grpcio==1.47.0
    - h5py==3.7.0
    - idna==3.3
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - numpy==1.23.1
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.2.0
    - pipreqs==0.4.11
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - sqlalchemy==1.4.40
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yarg==0.1.9